// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FollowList       string
	Reactions        string
	SchemaMigrations string
	TextNotes        string
	UsersMetadata    string
}{
	FollowList:       "follow_list",
	Reactions:        "reactions",
	SchemaMigrations: "schema_migrations",
	TextNotes:        "text_notes",
	UsersMetadata:    "users_metadata",
}
